import { JobsEnum } from "~/types";
import { undefined } from "zod";
import {
  BluelightIcon,
  BluelightLargeIcon,
  HodlTreeIcon,
  HodlTreeLargeIcon,
  IzzzioIcon,
  IzzzioLargeIcon,
  NoWorkplaceIcon,
  NoWorkplaceLargeIcon,
  SvoiIcon,
  SvoiLargeIcon,
  TokenStationIcon,
  TokenStationLargeIcon,
} from "~/components/icons/workplace-icons";
import {
  BluelightDescription,
  FuturestateDescription,
  HodlTreeDescription,
  IzzzioDescription,
  MyOwnDescription,
  NoDescriptionYet,
  SvoiDescription,
  TokenstationDescription,
  VniinsDescription,
} from "~/components/descriptions/descriptions";
import {
  AzureIcon,
  BashIcon,
  BitBucketIcon,
  DebianIcon,
  DockerIcon,
  EthereumIcon,
  EverscaleIcon,
  GithubIcon,
  GitLabIcon,
  HardhatIcon,
  KubernetesIcon,
  KustomizeIcon,
  LensIcon,
  MongoDBIcon,
  NestJSIcon,
  NodeJSIcon,
  OpenTelemetryIcon,
  PrometheusIcon,
  PythonIcon,
  SentryIcon,
  SolidityIcon,
  TheGraphIcon,
  TronIcon,
  TSLangIcon,
  UbuntuIcon,
} from "~/components/icons/tech-icons";
import React from "react";

export type JobDescription = {
  icon: () => React.ReactNode;
  largeIcon: () => React.ReactNode;
  position: string;
  startDate: Date;
  endDate?: Date;
  description: () => React.ReactNode;
  stack: (() => React.ReactNode)[];
};

export const jobs: Record<JobsEnum, JobDescription | undefined> = {
  Futurestate: {
    icon: NoWorkplaceIcon,
    largeIcon: NoWorkplaceLargeIcon,
    position: "Blockchain developer",
    startDate: new Date("2024-03-01"),
    description: FuturestateDescription,
    stack: [
      EthereumIcon,
      SolidityIcon,
      HardhatIcon,
      TheGraphIcon,
      DockerIcon,
      NodeJSIcon,
      TSLangIcon,
      UbuntuIcon,
      GitLabIcon,
    ],
  },
  HodlTree: {
    icon: HodlTreeIcon,
    largeIcon: HodlTreeLargeIcon,
    position: "Blockchain developer",
    startDate: new Date("2022-01"),
    endDate: new Date("2022-05"),
    description: HodlTreeDescription,
    stack: [EthereumIcon, SolidityIcon, HardhatIcon, GithubIcon],
  },
  IZZZIO: {
    icon: IzzzioIcon,
    largeIcon: IzzzioLargeIcon,
    position: "Blockchain developer",
    startDate: new Date("2020-03"),
    endDate: new Date("2020-06"),
    description: IzzzioDescription,
    stack: [NodeJSIcon, BashIcon, GithubIcon],
  },
  MyOwn: {
    icon: NoWorkplaceIcon,
    largeIcon: NoWorkplaceLargeIcon,
    position: "CEO & CTO & The one and only employee",
    startDate: new Date("1999-09-23"),
    description: MyOwnDescription,
    stack: [],
  },
  SVOIdev: {
    icon: SvoiIcon,
    largeIcon: SvoiLargeIcon,
    position: "Blockchain developer",
    startDate: new Date("2020-09"),
    endDate: new Date("2022-02"),
    description: SvoiDescription,
    stack: [
      EverscaleIcon,
      NodeJSIcon,
      MongoDBIcon,
      BashIcon,
      UbuntuIcon,
      GithubIcon,
    ],
  },
  Tokenstation: {
    icon: TokenStationIcon,
    largeIcon: TokenStationLargeIcon,
    position: "Blockchain developer",
    startDate: new Date("2021-09"),
    endDate: new Date("2024-01"),
    description: TokenstationDescription,
    stack: [
      TronIcon,
      EthereumIcon,
      SolidityIcon,
      HardhatIcon,
      NodeJSIcon,
      PythonIcon,
      MongoDBIcon,
      DockerIcon,
      UbuntuIcon,
      GithubIcon,
    ],
  },
  Bluelight: {
    icon: BluelightIcon,
    largeIcon: BluelightLargeIcon,
    position: "Blockchain developer",
    startDate: new Date("2022-11-25"),
    endDate: new Date("2024-02-29"),
    description: BluelightDescription,
    stack: [
      EthereumIcon,
      SolidityIcon,
      HardhatIcon,
      TheGraphIcon,
      NestJSIcon,
      OpenTelemetryIcon,
      SentryIcon,
      PrometheusIcon,
      BashIcon,
      DockerIcon,
      KubernetesIcon,
      KustomizeIcon,
      LensIcon,
      AzureIcon,
      UbuntuIcon,
      BitBucketIcon,
    ],
  },
  Vniins: {
    icon: NoWorkplaceIcon,
    largeIcon: NoWorkplaceLargeIcon,
    position: "DevOps engineer",
    startDate: new Date("2018-12"),
    endDate: new Date("2022-06"),
    description: VniinsDescription,
    stack: [BashIcon, DockerIcon, DebianIcon],
  },
};
